### ISSUE TITLE
Information about Data Preperation and Input

### ISSUE THREAD

**Issue by bensuucar** [xcyan/neurips18_hierchical_image_manipulation#2]
Dear Xcyan,

In order to use your model with my own dataset, I am trying to understand your architecture. Could you please provide more details and explanation regarding data-processing steps and the inputs model takes? 
Thank you!

**Comment by xcyan** [comment]
Thanks for your question! Can you be more specific at which line you don’t understand? We will try to clarify as much as possible.

**Comment by bensuucar** [comment]
In my dataset, I have real images together with their semantic labels. However when I look at pre-processing steps of ADE20K dataset, it seems I need much more information than just having semantic labels. Because pre-processing creates train_bbox, train_label, train_ins folders. 
What information do I need in my own dataset besides semantic labels? (My images are composed of 5 different objects which do not have any sub-parts associated with them)
What is in json files under train_bbox folder?
What is the difference between train_inst and train_label folders?

**Comment by xcyan** [comment]
For data preprocessing, we used both instance segmentation and semantic segmentation information. 

That’s why you see two different folders.

My suggestion is to run the preprocessing code on either cityscape or ade20k dataset, then you should be able to figure out.

**Comment by xcyan** [comment]
Assigned to @thomasehuang who implemented the script on ADE20K dataset.

**Comment by bensuucar** [comment]
I have been exploring the possibility of using only semantic segmentation information. The objects in my images are separate objects and they do not share any boundaries but I do not have any instance level information. Would it be possible to use only semantic segmentation information?
If so, what should I do with '_inst' path and related information asked in the network? Because even though I specify no_instance, it asks for instance segmentation images. 
Besides, should I specify label_nc = 0 for only using semantic information?

**Comment by thomasehuang** [comment]
If you know that your objects are separate, you can create the instance segmentation by assigning each object a unique ID. The .json files in the _bbox directory contains the mapping from the unique ID to class ID. I suggest maybe running the existing script first and seeing what the resulting data looks like. 

label_nc specifies the number of object classes + 1 (for the background).
