### ISSUE TITLE
Error when using pre-trained models

### ISSUE THREAD

**Issue by bensuucar** [xcyan/neurips18_hierchical_image_manipulation#3]
In "Inference using a Pre-trained Box-to-Layout Generator" part, after dowloanding the models,  I cannot proceed when I run "vis_box2mask.py" because of the following error:

  File "vis_box2mask.py", line 74   
  label_path = data['label_path']    
 SyntaxError: invalid syntax

The same goes for "Inference using a Pre-trained Layout-to-Image Generator" with the error of;
 
  File "vis_mask2image.py", line 5, in <module>
    from options.mask2image_test_options import MaskToImageTestOptions as TestOptions
  File "/data/Bensu/neurips18_hierchical_image_manipulation-master/options/mask2image_test_options.py", line 3, in <module>
    from mask2image_base_options import MaskToImageOptions
ModuleNotFoundError: No module named 'mask2image_base_options'

I doubled checked to be sure that I have mask2image_base_options script under that folder. But the second error might be because I couldn't proceed with box-to-layout.

Could you please help me to proceed?

**Comment by xcyan** [comment]
Hi Are you using python 2 or python 3?

**Comment by bensuucar** [comment]
I am using python 3

**Comment by xcyan** [comment]
Can you try python2.7 and see if the problem is resolved or not?

**Comment by bensuucar** [comment]
Dear Xcyan,
I tried python2.7 but I am still getting the same error unfortunately.

**Comment by bensuucar** [comment]
I found the error. 

For the first error, you are missing ]) in line 73 of vis_box2mask.py

And the second error is solved by adding changing line 3 of box2mask_test_options.py to from options.box2mask_base_options import BoxToMaskOptions

**Comment by xcyan** [comment]
Thanks for spotting this bug. We've fixed the visualization script.
