### ISSUE TITLE
How to specify bounding box and class labels while testing

### ISSUE THREAD

**Issue by bensuucar** [xcyan/neurips18_hierchical_image_manipulation#4]
Dear Xcyan,

I would like to ask how I can specify the place and the type of the object to add/remove. In the article, it is stated that it is possible to do so by specifying bounding box coordinates and class labels. However, I couldn't find it on the code.
Thanks!

**Comment by xcyan** [comment]
You can simply cropped the object of interest and fed into this line:
https://github.com/xcyan/neurips18_hierchical_image_manipulation/blob/master/vis_box2mask.py#L38

**Comment by MartiGrau** [comment]
Hi!
Good work with the development of this net!
I just have some problem to deal with the specification of the class label while testing the ade20k dataset.
My objective is to generate/sintethisize 'wall' or 'floor' in the same place where there was some object (Ex: Generate floor in the same place where the bed was).
Could you detail the explanation of "crop the object of interest and feed into this line"?
https://github.com/xcyan/neurips18_hierchical_image_manipulation/blob/master/vis_box2mask.py#L38

I'm wondering in which file should modify and if there are some relation with the preprocess_ade.py file.

Sorry if the answer is too ovious,
Thanks!
