### ISSUE TITLE
bbox_cls = bbox_cls if bbox_cls is not None else self.opt.label_nc-1

### ISSUE THREAD

**Issue by bensuucar** [xcyan/neurips18_hierchical_image_manipulation#8]
Could you please explain why it is label_nc-1 in this line 

https://github.com/xcyan/neurips18_hierchical_image_manipulation/blob/20dd4f17adb78b1fe4c898b78be344482e337438/data/segmentation_dataset.py#L108

bbox_cls = bbox_cls if bbox_cls is not None else self.opt.label_nc-1

Thanks!

**Comment by xcyan** [comment]
I think you are referring to the background class.

**Comment by xcyan** [comment]
Closing this issue.
